# Generated by Django 5.1.3 on 2024-12-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='deleted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
