# Generated by Django 5.1.4 on 2024-12-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='app_token',
            field=models.TextField(null=True),
        ),
    ]
